name: chatgpt_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  chat_gpt_sdk: ^2.2.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  riverpod_annotation: ^2.3.3
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo/
    - assets/animations/
    - assets/splash/
flutter_native_splash:
  background_image: "assets/images/icon/icon.png"
  color: "#ffffff"
  android_12:
    image: assets/images/icon/icon.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
